// <auto-generated />
namespace MySparePart.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class clientPartDelete : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(clientPartDelete));
        
        string IMigrationMetadata.Id
        {
            get { return "201506301716330_clientPartDelete"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
